### ISSUE TITLE
Some help please

### ISSUE THREAD

**Issue by posixx** [Hypfer/ICantBelieveItsNotValetudo#1]
Could we get some description about this new setup? For instance, I have 2 roborocks running in my house, how to configure this using the separate project? Also how does this new service get info from the roborocks? Through MQTT?

**Comment by Hypfer** [comment]
Documentation is rather sparse indeed atm 😕

Basically you need to run two instances of this application with slightly different configuration files.
Starting with Valetudo 0.3.1, the robot is pushing the raw data to MQTT on `topicPrefix/identifier/map_data` which defaults to `valetudo/rockrobo/map_data`.

If you compare the configuration file seen in this repos `readme.md` to the configuration on your robot it should be fairly easy to understand.


To run this software, you can either just `git clone`, ``npm install`, `npm start`, or use the provided Dockerfile to deploy it in a container

**Comment by posixx** [comment]
Tnx for explaination. I'm using openhab with MQTT; you mention it wil push raw data to mqtt; so this is different from a map drawing? So this isn't a PNG already?

**Comment by posixx** [comment]
Thx for explaining. It can use webserver for image retrieval, but does it also send MQTT message with image back on a topic? So we don't have to use manual retrieval. With v0.30 i have realitime map updaters during cleaning so it would be nice to keep that

**Comment by Hypfer** [comment]
It also sends the Map as PNG to the MQTT Topic and does the Home Assistant MQTT Autoconfiguration.

I just added the webserver for FHEM etc. It's completely optional

**Comment by posixx** [comment]
Nice:-) Going to upgrade now..

**Comment by posixx** [comment]
oh, another option would be nice for this and valetudo: disable autodiscovery for homeassistant. Right now it keeps finding new items in openhab even when selecting hide devices..

**Comment by Hypfer** [comment]
That only happens if you're using different identifiers than before. Otherwise it should simply overwrite the old stored MQTT Message and HA doesn't detect a "new" device

**Comment by posixx** [comment]
Nice it works perfectly. running 2 npm instances using pm2, still having realtime updates of the map on my openhab dashboard!

about the autodiscovery; i don't change identifiers at all, but it is still redetected in OpenHAB

**Comment by AL0F** [comment]
Hey there! What I don't understand and should be mentioned somewhere in the Readme: where should this companion be running? On the robot? Or on a pi? If in the robot: I even can't install NPM due to limited Drive space on the robot - how to start this?
