### ISSUE TITLE
Can't launch Valetudo Floorplan

### ISSUE THREAD

**Issue by Isking007** [Hypfer/ICantBelieveItsNotValetudo#10]
Hi, i've installed valetudo's addon in Hassio on pi3. I have rockrobo s50 with firmware 1910 with valetudo. After start of the addon i have "not found" in hassio.
`{
  "identifier": "rockrobo",
  "topicPrefix": "valetudo",
  "autoconfPrefix": "homeassistant",
  "broker_url": "mqtt://user:pass@192.168.0.190:1883",
  "caPath": "",
  "mapSettings": {
    "drawPath": true,
    "drawCharger": true,
    "drawRobot": true,
    "border": 2,
    "scale": 4
  },
  "mapDataTopic": "valetudo/rockrobo/map_data",
  "minMillisecondsBetweenMapUpdates": 10000,
  "publishMapImage": true
}`

**Comment by darkkatarsis** [comment]
try log via ssh to rockrobo and enable mqtt in /mnt/data/valetudo/config.json

**Comment by Isking007** [comment]
Thanks, it helped. But in hassio I see card in big scale and cannot operate the robot. Only by new entity. Could I operate the robot by map of valetudo in hassio?

**Comment by darkkatarsis** [comment]
No, but you can try this https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card

**Comment by Isking007** [comment]
Thanks, I've already use this card for a long time)) and now have a problem on defining of coordinates zones. I take coordinates from config of valetudo and insert in map card config, but on card have mirrored zones. Could you help?
