### ISSUE TITLE
Use robot to build wifi heatmap

### ISSUE THREAD

**Issue by homefefeld** [Hypfer/ICantBelieveItsNotValetudo#12]
This is to suggest an enhancement. Please let me know if you would be able to work on it. 
I was wondering if we could use the robot to capture wifi information (RSSI, noise, RX/TX rate) while hoovering.
We could then push this data over MQTT and build a very accurate wifi heat map.
This would be very good to have to place the access points in the right location.
<img width="630" alt="image" src="https://user-images.githubusercontent.com/3512839/71321100-472c7d80-24b5-11ea-8c6e-eab16f1fca83.png">

**Comment by bruvv** [comment]
It can be done with the latest release: https://github.com/ccoors/Valeronoi
