### ISSUE TITLE
Reorganize configuration

### ISSUE THREAD

**Issue by SvenFestersen** [Hypfer/ICantBelieveItsNotValetudo#17]
While working on the documentation I realized that the configuration object does not have a logical structure: the map settings are a child of the MQTT configuration and also contain an unused option ("border"). I would like to refactor the configuration:
* move `mqtt.mapSettings` to the top level
* remove `mapSettings.border`
* and while I'm on it: address issue #11 and make the `Configuration` object write `config.json` only if it does not exist

Since this is a breaking change for existing configurations, I would like to know if there are any objections to this plan?

**Comment by Hypfer** [comment]
Since it's version 0.2.0, I guess that you can just break it. Maybe add a console.info with that information

**Comment by m4rk89** [comment]
Hi!

I have installed this as an addon from HA's store. Could you help me what should I use for the webserver? webserver.enabled: true is not working anymore if I am configuring it from the HA's interface.
