### ISSUE TITLE
Automatically crop whitespace

### ISSUE THREAD

**Issue by LordMike** [Hypfer/ICantBelieveItsNotValetudo#21]
As foretold by the docs, I have huge blobs of whitespace on my map. Would it be possible to create a feature that automatically crops this, by removing all-white rows and columns of pixels?

![image](https://user-images.githubusercontent.com/1027111/76685694-09ec0d80-6616-11ea-9a6d-6f3c71152dcc.png)

**Comment by LordMike** [comment]
Note, I've found a quick way to do this. [`Jimp` has an `autocrop` feature](https://github.com/oliver-moran/jimp/blob/master/packages/plugin-crop/README.md).

**Comment by alceasan** [comment]
Thanks @LordMike, it works like a charm. Manual cropping doesn't work very well, but using autocrop isn't necessary in my opinion.

We could use a new conf variable to set autocrop, and just make the image.autocrop() call in Tools.js depending on its value.
