### ISSUE TITLE
Help needed with portainer on Hass.io

### ISSUE THREAD

**Issue by The-May** [Hypfer/ICantBelieveItsNotValetudo#25]
Hi,

I tried running a docker container with portainer inside Home Assistant (Hass.io).
Unfortunately I cannot get it running because I cannot implement my customized config.json at all.
I'm a very beginner though and despite the official docs how to do this are pretty confusing and/or do not help me at all unfortunately.
I would really appreciate a (maybe step by step?) help so I could contribute a further detailed instruction for the beginners that struggled like me.
Thanks in advance.

**Comment by randy993** [comment]
Sounds familiar... The installation in HA by using Portainer is slightly different than a regular docker install.

In short;
- Create a config file in /share/ICantBelieveItsNotValetudo/config.json with your settings
- Install Portainer
- Add new ICantBelieveItsNotValetudo container
- Forward port (3000:3000) in the Manual network port publishing setting
- Map container json: Advanced container settings -> volumes ->
  Container: Path in container: /app/config.json and select bind option;
  Host: /mnt/data/supervisor/share/ICantBelieveItsNotValetudo/config.json and I think read-only will do.

Let me know if this helped. Maybe it's good to add the HomeAssistant path to installation notes as its slightly different than just /share/...

**Comment by The-May** [comment]
Hey randy993,

thanks for the help.
Unfortunately I coult not get it running.

I am goint to sum up what I did:

1. Created Volume with a name:
![1](https://user-images.githubusercontent.com/47433911/92305078-111c2480-ef84-11ea-90f6-2dc50d2a0231.png)

The Volume has following details:

![2 0 1](https://user-images.githubusercontent.com/47433911/92305190-36f5f900-ef85-11ea-8e56-de23f482d7f2.png)



2. Then I Created the Container with the parameters that I could figure out:
![2](https://user-images.githubusercontent.com/47433911/92305120-77a14280-ef84-11ea-913a-a1b13325abb8.png)

An SMB directory gets created automatically in the \share folder of my Home assistant Directory:

![2 1](https://user-images.githubusercontent.com/47433911/92305161-dbc40680-ef84-11ea-902b-5e130a368ac1.png)


3. I am adding my Credentials to the config.json file and I add them in this newly created folder


4. I check the logs and I get following error:


```
> i-cant-believe-its-not-valetudo@0.2.0 start /app,
> node app.js,
Loading configuration file: /app/config.json,
Invalid configuration file!,
{ Error: EISDIR: illegal operation on a directory, read,
    at Object.fs.readSync (fs.js:675:18),
    at tryReadSync (fs.js:540:20),
    at Object.fs.readFileSync (fs.js:583:19),
    at new Configuration (/app/lib/Configuration.js:45:72),
    at Object.<anonymous> (/app/app.js:6:14),
    at Module._compile (module.js:653:30),
    at Object.Module._extensions..js (module.js:664:10),
    at Module.load (module.js:566:32),
    at tryModuleLoad (module.js:506:12),
    at Function.Module._load (module.js:498:3) errno: -21, code: 'EISDIR', syscall: 'read' },
npm ERR! code ELIFECYCLE,
npm ERR! errno 1,
npm ERR! i-cant-believe-its-not-valetudo@0.2.0 start: `node app.js`,
npm ERR! Exit status 1,
```


I guess the config.json file is somehow wrongly mapped but I cannot figure out what is wrong.
Do you maybe know what the Issue might be?
Thanks in advance
