### ISSUE TITLE
How to rotate the map?

### ISSUE THREAD

**Issue by cotwild** [Hypfer/ICantBelieveItsNotValetudo#28]
Fist of all.. Amazing work! Thanks a lot. I am using two mapper instances for my two roborock s2 on each floor, but sadly one map isn't rotated correctly...

There doesn't seem to be an option to rotate map in valetudo RE, nor in home assistant. Is there an option to rotate the map?

**Comment by dodvarko** [comment]
Taken care of in https://github.com/Hypfer/ICantBelieveItsNotValetudo/pull/30, not sure how to link these tho
