### ISSUE TITLE
No map data in MQTT

### ISSUE THREAD

**Issue by Muyz** [Hypfer/ICantBelieveItsNotValetudo#3]
Hi,

With this config file on the robot:

`
{
  "spots": [],
  "areas": [],
  "mqtt": {
    "enabled": true,
    "identifier": "rockrobo",
    "topicPrefix": "valetudo",
    "autoconfPrefix": "homeassistant",
    "broker_url": "mqtt://192.168.0.9:1883",
    "provideMapData": true
  },
  "dummycloud": {
    "spoofedIP": "203.0.113.1",
    "bindIP": "127.0.0.1"
  },
  "map_upload_host": "http://127.0.0.1"
}
`

I see data being posted to my MQTT broker on /valetudo/rockrobo/attributes and /homeassistant/vacuum/valetudo_rockrobo/config. However, when I start cleaning, no map data appears. How long does it take before map data should appear in the MQTT broker? What could be wrong?

Valetudo 0.3.1 running

**Comment by thundergreen** [comment]
@Muyz try removing the port after mqtt broker url. Did u also install the compagnion for valetudo?

**Comment by itsexe** [comment]
I have the same issue. I'm also running Valetudo 0.3.1 on firmware v11_001748.

This is my config file for this project:
`{
  "mqtt": {
    "identifier": "rockrobo",
    "topicPrefix": "valetudo",
    "autoconfPrefix": "homeassistant",
    "broker_url": "mqtt://mymqttbroker",
    "caPath": "",
    "mapSettings": {
      "drawPath": true,
      "drawCharger": true,
      "drawRobot": true,
      "border": 2,
      "scale": 4
    },
    "mapDataTopic": "valetudo/rockrobo/map_data",
    "minMillisecondsBetweenMapUpdates": 10000,
    "publishMapImage": true
  },
  "webserver": {
    "enabled": true,
    "port": 3000
  }
}`

This is my config file on the robot:
`{
  "spots": [],
  "areas": [],
  "mqtt": {
    "enabled": true,
    "identifier": "rockrobo",
    "topicPrefix": "valetudo",
    "autoconfPrefix": "homeassistant",
    "broker_url": "mqtt://mymqttbroker",
    "mapSettings": {
      "drawPath": true,
      "drawCharger": true,
      "drawRobot": true,
      "border": 2,
      "scale": 4
    }
  },
  "dummycloud": {
    "spoofedIP": "203.0.113.1",
    "bindIP": "127.0.0.1"
  },
  "map_upload_host": "http://127.0.0.1"
}`

Have you tried sending the contents of [default_map.json](https://github.com/Hypfer/Valetudo/blob/master/lib/res/default_map.json) to your MQTT broker? That works for me.

**Comment by MrSolo570** [comment]
Hello,
I have the same problem. I have valetudo re installed on version 0.9.0 and my robot configured like this:

`  "mqtt": {
    "enabled": true,
    "identifier": "tachikoma",
    "topicPrefix": "valetudo",
    "autoconfPrefix": "homeassistant",
    "broker_url": "mqtt://mqtt:mqtt@192.168.188.45",
    "provideMapData": true,
    "mapSettings": {
      "drawPath": true,
      "drawCharger": true,
      "drawRobot": true,
      "border": 2,
      "scale": 4
    },
    "caPath": ""
  },
  "dummycloud": {
    "spoofedIP": "203.0.113.1",
    "bindIP": "127.0.0.1"
  },
  "webInterface": {
    "localization": "en",
    "hideMapReload": true,
    "style": ""
  },
  "httpAuth": {
    "enabled": false,
    "username": "valetudo",
    "password": "valetudo"
  },
  "telegramBot": {
    "enabled": false,
    "token": "",
    "password": "",
    "host": "",
    "proxy": "",
    "clients": [],
    "sendConsumables": true,
    "sendConsumablesEvery": false
  },
  "allowSSHKeyUpload": true,
  "map_upload_host": "http://127.0.0.1"`

When I listend to mqtt topic "valetudo/#" I can see this but can't get no map data:
`Message 14 received on valetudo/tachikoma/state at 9:02 PM:
{
    "state": "docked",
    "battery_level": 100,
    "fan_speed": "max"
}
QoS: 0 - Retain: true
Message 13 received on valetudo/tachikoma/attributes at 9:02 PM:
{
    "cleanTime": "169.5",
    "cleanArea": "8805.5",
    "cleanCount": 501,
    "last_run_stats": {
        "startTime": 1582372097000,
        "endTime": 1582373128000,
        "duration": 968,
        "area": "15.0",
        "errorCode": 0,
        "errorDescription": "No error",
        "finishedFlag": true
    },
    "currentCleanTime": "16.1",
    "currentCleanArea": "15.0",
    "mainBrush": "130.5",
    "sideBrush": "30.5",
    "filter": "144.2",
    "sensor": "27.7",
    "state": "docked",
    "valetudo_state": {
        "id": 8,
        "name": "Charging"
    }
}`

I have installed Valetudo in the first place with a auto-built firmware from [https://dustbuilder.xvm.mit.edu/](url) and afterwards copied the .deb-installation-file for valetudo re  onto the robot and installed verything via ssh.

How can I fix the no map problem via mqtt? Thank you

**Comment by r1sim** [comment]
Valetudo RE is not supported by `ICantBelieveItsNotValetudo`. This project is for the original Valetudo. Try https://github.com/rand256/valetudo-mapper
