### ISSUE TITLE
High cpu usage on valetudo 0.6.1

### ISSUE THREAD

**Issue by ghost** [Hypfer/ICantBelieveItsNotValetudo#32]
Every since upgrading to valetudo 0.6.1, the mapper consumes about a full core on a i7-7700T
The config beeing
```
{
  "mapsettings": {
    "drawCharger": true,
    "drawPath": true,
    "drawRobot": true,
    "scale": 4
  },
  "mqtt": {
    "autoconfPrefix": "homeassistant",
    "broker_url": "mqtt://mosquitto.homeassistant",
    "identifier": "Roborock",
    "mapDataTopic": "valetudo/Roborock/map_data",
    "minMillisecondsBetweenMapUpdates": 5000,
    "publishMapImage": true,
    "topicPrefix": "valetudo"
  },
  "webserver": {
    "enabled": false,
    "port": 3000
  }
}
```
And the usage looks like this
<img width="1201" alt="Screenshot 2020-08-04 at 12 49 46" src="https://user-images.githubusercontent.com/18247748/89285650-0b63b400-d651-11ea-908f-9e75a75d4a37.png">

**Comment by Hypfer** [comment]
Yep.

The current implementation performs abysmal and only exists at all because I wanted to avoid "but but but RE does thing" nagging.
I don't have any use for this service

**Comment by kubiq** [comment]
You can make the map smaller with scale 2 or so, that will help for now

**Comment by Hypfer** [comment]
Thanks to @mikispag this is now solved
