### ISSUE TITLE
Publish Docker image

### ISSUE THREAD

**Issue by twsl** [Hypfer/ICantBelieveItsNotValetudo#43]
The repo does not publish own docker images and images of others are outdated.

**Comment by Hypfer** [comment]
See PR #44

**Comment by rickardrockard** [comment]
I have a fork of this project without any modifications with a bot keeping it up to date, so that my docker repo gets automatically updated with any commits https://hub.docker.com/repository/docker/rickardrockard/icantbelieveitsnotvaletudo

**Comment by twsl** [comment]
Not really a fan of your reasoning, as I do not understand it, but I'll just leave my fork online and up to date, so that's almost the same
