### ISSUE TITLE
webserver option removed?

### ISSUE THREAD

**Issue by Zaschii** [Hypfer/ICantBelieveItsNotValetudo#54]
Hi, 

iam using ...

```
  "webserver": {
    "enabled": true,
    "port": 3456 }
```

in my config to provige a image file within the URL http://IP:PORT/api/map/image.

Today i made a update to the actual version and it seems that there is no webserver running.

Within the log there is no info about the webserver...
```
> i-cant-believe-its-not-valetudo@2021.2.1 start
> node app.js

Loading configuration file: /root/valetudomap/ICantBelieveItsNotValetudo/config.json
Connecting to MQTT broker...
Connected to MQTT broker.
Drawing map...
drawMap: 335.118ms
Map drawn.
Map published.
Skipping map generation as it has not changed.
```

did you remove the webserver component?

How could i provide the png or svg file at my visualisation server?

Thanks and BR

**Comment by Zaschii** [comment]
Any Feedback please. 

BR

**Comment by Zaschii** [comment]
Is there anybody with the same problem?
i didnt find any informations in the changelog about that.

could you please provide a solution, at the moment my map visualisation is not working in cause of that.

BR,

**Comment by Hypfer** [comment]
Nagging for three days in a row and demanding an answer in less than 24h like this is a commercial product will not increase the priority of your issue but decrease it.

**Comment by Zaschii** [comment]
nice answer....thanks.

its clear that this is not a commercial product and iam very thankful to that complete valetudo and ICantBelieveItsNotValetudo project, you are doing a great job!

but iam not nagging, iam looking forward to an answer and comment like "i will take a look at this" and no marking my comments as spam would avoid this.

**Comment by Zaschii** [comment]
could you already estimate, when you will find some time to analyse this? Thanks and BR
