### ISSUE TITLE
Howto Debug during Setup

### ISSUE THREAD

**Issue by dcbo** [Hypfer/ICantBelieveItsNotValetudo#58]
Hi, I'm Dario from Germany,

I hope this is the right place to ask.

I found this nice Project and I tried to set it up but I run into problems, 
thus I have a question regarding the logLevel, which I think I'm not able to change,

### What I did: ### 
```javascript
icantbelieveitsnotvaletudo:
    build:
      context: ./ICantBelieveItsNotValetudo/
      dockerfile: Dockerfile
    container_name: "iot-ICantBelieveItsNotValetudo"
    restart: unless-stopped
    user: "1000:1000"   
    networks:
      - proxy      
    ports:
      - "3000:3000"
    volumes:
      - ./ICantBelieveItsNotValetudo/config.json:/app/config.json
```
Then i created an empty file 
```touch ./ICantBelieveItsNotValetudo/config.json```
And fired up the Container.
```docker-compose up icantbelieveitsnotvaletudo```
A default `config.json` is generated and I edited it to my needs and everything seems OK (I get no Errors in the Log)
But nothing happens, The Webserver returns `Not Found` when requesting `http://[IP]:3000/api/map/image`
and I don't see any messages published by icantbelieveitsnotvaletudo 

### Here is my Question: ###
To enable more Debugging-Output i changed `logLevel` in `config.json` to 
`"logLevel": "trace"`
But it seems to have no effect.

**What am I doing wrong?**

**Comment by idittansikte** [comment]
Change README as well? That got me fooled for hours!

**Comment by rossiluis22** [comment]
thanks!! also spent a lot of hours, and finally the problem was that /MapData/map-data... please update the README so people don't get confused.
