### ISSUE TITLE
corrupted double-linked list

### ISSUE THREAD

**Issue by marcelfischer** [Hypfer/ICantBelieveItsNotValetudo#62]
I updated today to the newest Version and switched to nodejs v14.17.0
Now after starting ICantBelieveItsNotValetudo, a few minutes or seconds later it crashes with "corrupted double-linked list". But map drawing works a few times:
May 24 10:30:03 homesrv01 node[21196]: [2021-05-24T08:30:03.029Z] [INFO] Drawing map...
May 24 10:30:03 homesrv01 node[21196]: [2021-05-24T08:30:03.801Z] [INFO] Map drawn in 770.955856 ms
May 24 10:30:03 homesrv01 node[21196]: [2021-05-24T08:30:03.803Z] [INFO] Map published.
May 24 10:30:13 homesrv01 node[21196]: [2021-05-24T08:30:13.004Z] [INFO] Drawing map...
May 24 10:30:13 homesrv01 node[21196]: [2021-05-24T08:30:13.719Z] [INFO] Map drawn in 714.423341 ms
May 24 10:30:13 homesrv01 node[21196]: [2021-05-24T08:30:13.721Z] [INFO] Map published.
May 24 10:30:23 homesrv01 node[21196]: [2021-05-24T08:30:23.009Z] [INFO] Drawing map...
May 24 10:30:23 homesrv01 node[21196]: [2021-05-24T08:30:23.663Z] [INFO] Map drawn in 652.773113 ms
May 24 10:30:23 homesrv01 node[21196]: [2021-05-24T08:30:23.665Z] [INFO] Map published.
May 24 10:30:33 homesrv01 node[21196]: [2021-05-24T08:30:33.011Z] [INFO] Drawing map...

**Comment by Hypfer** [comment]
That's definitely either the runtime or the native part of the canvas dependency dying there, since there's no such thing as a double-linked list in js

**Comment by marcelfischer** [comment]
Hmm looks like https://github.com/Hypfer/ICantBelieveItsNotValetudo/pull/61 fixed it.
But when the robots runs, it happens again:
malloc(): smallbin double linked list corrupted

Is there a recommended nodejs Version?
nodejs -v
v14.17.0
