### ISSUE TITLE
Request: Multiple robot support

### ISSUE THREAD

**Issue by thetic** [Hypfer/ICantBelieveItsNotValetudo#64]
It would be nice if I could generate maps for multiple robots running valetudo from a single config of this tool.

**Comment by Hypfer** [comment]
Why not just run this tool multiple times?

**Comment by thetic** [comment]
I'm running it as a [Home Assistant Add-on](https://github.com/Poeschl/Hassio-Addons/tree/master/ICantBelieveItsNotValetudo) which makes it near impossible to create multiple instances.

**Comment by Strohhutpat** [comment]
I'm also using the [Home Assistant Add-on](https://github.com/Poeschl/Hassio-Addons/tree/master/ICantBelieveItsNotValetudo) 
and have 2 S5 Bots 
(first world problems ^^)

**Comment by derrohrbach** [comment]
For now you can use my forked addon repo to add a second instance to HA

https://github.com/derrohrbach/Hassio-Addons

**Comment by derrohrbach** [comment]
I really did not plan to maintain my fork. It would be nice if we could find a longer term solution.

**Comment by Hypfer** [comment]
"We could find" 
more like
"Hey you solve my problem. Now."

There is no officially supported hassio add-on => There is no issue

**Comment by derrohrbach** [comment]
No it does not. First of all I aleady did work by making a second repo. Second of all I would be glad to help find a solution. Your hostility sounds more like what contaminated open source, but please let's not fight over this and instead solve thr problem multiple people have. Please tell me, who maintains the hassio addon? so i can contact them. I think we should first discuss a sustainable approch. And please don't assume, that i don't want to contribute!

**Comment by Hypfer** [comment]
Please consider switching back to the cloud.

**Comment by Hypfer** [comment]
Just for reference

> please let's not fight over this and instead solve thr problem multiple people have

There is no problem. The problem is, that people don't want to use this software as it was intended.
"Finding a solution" simply means "go implement this feature that I want.", which won't be happening since you're not the manager of this project. You don't get to decide the scope.


>Your hostility sounds more like what contaminated open source

lol
