### ISSUE TITLE
Don't know how to install

### ISSUE THREAD

**Issue by dnl0319** [Hypfer/ICantBelieveItsNotValetudo#81]
Hallo everyone,

I was trying to install ICantBelieveItsNotValetudo but couldn't get it to work.

In the documentation is written, that you need to clone it from git and usw npm install. I tried it, but couldn't get it done. Can someone help me with this?

![grafik](https://user-images.githubusercontent.com/61114433/155527826-b7cf86e6-3e51-40b1-b2c9-0b765ff8256b.png)

**Comment by arnegue** [comment]
Hi you need to install npm first. I guess you're having apt installed:
`sudo apt install npm -y`
